# Generated by Django 2.2 on 2019-06-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellme', '0003_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/screenshots/', verbose_name='Screenshot'),
        ),
    ]
